### PR TITLE
Made private methods protected

### PR DESCRIPTION
**Pull request by Davidnadejdin**
Made private methods protected in order to be able to inherit

### CODE REVIEW

**Comment by fulopattila122** [comment]
This is not the behavior we want.
https://en.wikipedia.org/wiki/Open%E2%80%93closed_principle

**Comment by Davidnadejdin** [comment]
> This is not the behavior we want.
> https://en.wikipedia.org/wiki/Open%E2%80%93closed_principle

I don’t understand something, but how is it at all? Private properties and methods in an abstract class

**Comment by Davidnadejdin** [comment]
> A class is closed, since it may be compiled, stored in a library, baselined, and used by client classes. But it is also open, since any new class may use it as parent, adding new features. When a descendant class is defined, there is no need to change the original or to disturb its clients.

How can I reuse an implementation through inheritance when the required methods are private?

**Comment by fulopattila122** [comment]
via composition

**Comment by fulopattila122** [comment]
Alternatively, you can take this class (it's open source) and change the implementation the way you want. If there are other components that rely on konekt/enum, you can tell composer to use your package instead: https://getcomposer.org/doc/04-schema.md#replace

**Pull request closed without merging**
